

def prepare_func(all_data_dict):
    try:
        result = all_data_dict + "...preparing"
        print(result)
    except Exception as e:
        print(e)